version: "3.8"

services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:80"

  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"


  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
